//
//  ProblemsPanelController.swift
//  Pine
//
//  Project-scoped, revision-safe Problems panel aggregation (#1236).
//

import Foundation

/// Exact ownership of one visible editor document.
///
/// A URL alone is not an owner: the same file can be open in multiple panes,
/// and each pane can have an independently edited `EditorTab`. Including the
/// project token, pane, and tab prevents a result from being attributed to a
/// different window or editor after a tab switch.
nonisolated struct ProblemsDocumentOwner: Hashable, Sendable {
    let projectID: UUID
    let paneID: PaneID
    let tabID: UUID
    let uri: String
}

/// Live editor state used to prove that a diagnostic owner is still current.
nonisolated struct ProblemsDocumentState: Equatable, Sendable {
    let owner: ProblemsDocumentOwner
    let contentRevision: UInt64
    let isFocusedPane: Bool
}

/// Source-specific revision proof carried by every surfaced diagnostic.
nonisolated enum ProblemsDiagnosticRevision: Hashable, Sendable {
    /// Config validation ran against this exact `EditorTab.contentVersion`.
    case editor(UInt64)
    /// The server published this exact LSP version while the owning editor was
    /// at `contentRevision`.
    case lsp(documentVersion: Int?, contentRevision: UInt64)
}

/// Which producer supplied a diagnostic after semantic deduplication.
nonisolated enum ProblemsDiagnosticOrigin: Int, Hashable, Sendable {
    case config
    case lsp
}

nonisolated enum ProblemsSeverityFilter: String, CaseIterable, Identifiable,
    Sendable {
    case all
    case error
    case warning
    case info

    var id: String { rawValue }
}

nonisolated enum ProblemsPresentationState: Equatable, Sendable {
    case diagnostics
    case empty
    case disabled
    case unsupported
    case loading
    case unavailable
}

/// Stable semantic identity. Producer UUIDs are intentionally excluded:
/// `ValidationDiagnostic.id` is regenerated by parsers and cannot preserve
/// selection across a refresh.
nonisolated struct ProblemsDiagnosticID: Hashable, Sendable {
    let uri: String
    let line: Int
    let column: Int?
    let severityRank: Int
    let source: String
    let message: String
}

/// A flat diagnostic with an exact navigation owner and revision proof.
nonisolated struct ProblemsFlatDiagnostic: Identifiable, Equatable, Sendable {
    let id: ProblemsDiagnosticID
    let owner: ProblemsDocumentOwner
    let revision: ProblemsDiagnosticRevision
    let origin: ProblemsDiagnosticOrigin
    let diagnostic: ValidationDiagnostic

    var uri: String { owner.uri }
}

/// A deterministic file group consumed by the Problems panel view.
nonisolated struct ProblemsDiagnosticGroup: Identifiable, Equatable, Sendable {
    var id: String { uri }
    let uri: String
    let diagnostics: [ProblemsFlatDiagnostic]
}

/// A navigation request that remains project/pane/tab/revision scoped until
/// `ProjectManager` performs the final live-state check.
nonisolated struct ProblemsNavigationTarget: Equatable, Sendable {
    let owner: ProblemsDocumentOwner
    let revision: ProblemsDiagnosticRevision
    let line: Int
    let column: Int?
}

/// Project-scoped aggregate of all diagnostics shown in the Problems panel.
///
/// Config results are stored by exact document owner. Every read validates
/// them against a live document-state provider, so tab switches, removals,
/// pane moves, project mismatches, and newer content revisions all fail
/// closed. LSP results must additionally carry a server version proven by
/// `LSPManager`; ambiguous duplicate-URL owners are not guessed.
@MainActor
@Observable
final class ProblemsPanelController {

    private struct ConfigRecord {
        let revision: UInt64
        let diagnostics: [ValidationDiagnostic]
    }

    private struct Candidate {
        let entry: ProblemsFlatDiagnostic
        let isFocusedOwner: Bool
    }

    // MARK: - Identity and dependencies

    let projectID: UUID

    private weak var lspManager: LSPManager?
    private let injectedLSPDiagnosticsProvider:
        (@MainActor () -> [LSPProblemsDiagnostics])?
    private var documentStatesProvider:
        (@MainActor () -> [ProblemsDocumentState])?

    // MARK: - Stored config results

    private var configRecords: [ProblemsDocumentOwner: ConfigRecord] = [:]

    /// Observation token for producer or owner changes.
    private(set) var diagnosticsGeneration: UInt64 = 0

    // MARK: - Navigation and visibility

    private(set) var selectedDiagnosticID: ProblemsDiagnosticID?
    var isPanelVisible = false
    var severityFilter: ProblemsSeverityFilter = .all
    var sourceFilter: String?

    init(
        projectID: UUID = UUID(),
        lspManager: LSPManager? = nil,
        lspDiagnosticsProvider:
            (@MainActor () -> [LSPProblemsDiagnostics])? = nil
    ) {
        self.projectID = projectID
        self.lspManager = lspManager
        self.injectedLSPDiagnosticsProvider = lspDiagnosticsProvider
    }

    /// Re-binds the LSP manager (used by `ProjectManager` after init).
    func configure(lspManager: LSPManager?) {
        self.lspManager = lspManager
        refreshFromLSPDiagnostics()
    }

    /// Supplies the live visible-editor states for this project. Absence of a
    /// provider intentionally surfaces no diagnostics because ownership cannot
    /// be proven.
    func configureDocumentStatesProvider(
        _ provider: @MainActor @escaping () -> [ProblemsDocumentState]
    ) {
        documentStatesProvider = provider
        refreshDocumentOwnership()
    }

    /// Creates an owner token for a view in this controller's project.
    func documentOwner(paneID: PaneID, tabID: UUID, uri: String) -> ProblemsDocumentOwner {
        ProblemsDocumentOwner(
            projectID: projectID,
            paneID: paneID,
            tabID: tabID,
            uri: uri
        )
    }

    // MARK: - Producer refresh

    func refreshFromLSPDiagnostics() {
        diagnosticsGeneration &+= 1
        clearSelectionIfInvalidated()
    }

    /// Invalidates cached observation after a pane/tab/revision transition.
    /// Invalid records are also pruned so a long-lived project cannot retain
    /// results for closed tabs indefinitely.
    func refreshDocumentOwnership() {
        pruneInvalidConfigRecords()
        diagnosticsGeneration &+= 1
        clearSelectionIfInvalidated()
    }

    // MARK: - Config diagnostics

    func setConfigDiagnostics(
        _ diagnostics: [ValidationDiagnostic],
        owner: ProblemsDocumentOwner,
        contentRevision: UInt64
    ) {
        guard owner.projectID == projectID,
              currentState(for: owner)?.contentRevision == contentRevision else {
            return
        }

        let record = ConfigRecord(
            revision: contentRevision,
            diagnostics: diagnostics
        )
        if let existing = configRecords[owner],
           existing.revision == record.revision,
           existing.diagnostics == record.diagnostics {
            return
        }
        configRecords[owner] = record
        diagnosticsGeneration &+= 1
        clearSelectionIfInvalidated()
    }

    /// Removes only this pane/tab's result. Removing by URI would incorrectly
    /// erase a valid result owned by another pane showing the same file.
    func removeConfigDiagnostics(owner: ProblemsDocumentOwner) {
        guard owner.projectID == projectID,
              configRecords.removeValue(forKey: owner) != nil else {
            return
        }
        diagnosticsGeneration &+= 1
        clearSelectionIfInvalidated()
    }

    // MARK: - Aggregation

    var groupedDiagnostics: [ProblemsDiagnosticGroup] {
        let groups = Dictionary(grouping: filteredDiagnostics, by: \.uri)
        return groups.keys.sorted().map { uri in
            ProblemsDiagnosticGroup(
                uri: uri,
                diagnostics: groups[uri] ?? []
            )
        }
    }

    var flatDiagnostics: [ProblemsFlatDiagnostic] {
        // Track provider-only invalidations in Observation. The live state
        // itself arrives through closures and is not an observable property.
        _ = diagnosticsGeneration
        let states = normalizedDocumentStates()
        guard !states.isEmpty else { return [] }
        let statesByOwner = Dictionary(
            uniqueKeysWithValues: states.map { ($0.owner, $0) }
        )

        var candidates: [Candidate] = []
        candidates.reserveCapacity(
            configRecords.values.reduce(0) { $0 + $1.diagnostics.count }
        )

        for (owner, record) in configRecords {
            guard owner.projectID == projectID,
                  let state = statesByOwner[owner],
                  state.contentRevision == record.revision else {
                continue
            }
            for diagnostic in record.diagnostics {
                candidates.append(Candidate(
                    entry: makeEntry(
                        owner: owner,
                        revision: .editor(record.revision),
                        origin: .config,
                        diagnostic: diagnostic
                    ),
                    isFocusedOwner: state.isFocusedPane
                ))
            }
        }

        let statesByURI = Dictionary(grouping: states, by: { $0.owner.uri })
        for snapshot in currentLSPDiagnostics {
            // One URI in multiple visible editor panes has no exact LSP owner:
            // LSPManager synchronizes one buffer per URI. Do not route it to
            // whichever pane happens to be first in a dictionary.
            guard let owners = statesByURI[snapshot.uri],
                  owners.count == 1,
                  let state = owners.first,
                  state.contentRevision == snapshot.contentRevision else {
                continue
            }
            for diagnostic in snapshot.diagnostics {
                candidates.append(Candidate(
                    entry: makeEntry(
                        owner: state.owner,
                        revision: .lsp(
                            documentVersion: snapshot.documentVersion,
                            contentRevision: snapshot.contentRevision
                        ),
                        origin: .lsp,
                        diagnostic: diagnostic
                    ),
                    isFocusedOwner: state.isFocusedPane
                ))
            }
        }

        candidates.sort(by: candidatePrecedes)

        var seen: Set<ProblemsDiagnosticID> = []
        return candidates.compactMap { candidate in
            seen.insert(candidate.entry.id).inserted ? candidate.entry : nil
        }
    }

    var summary: DiagnosticsSummary {
        let flat = flatDiagnostics
        return DiagnosticsSummary(
            errorCount: flat.filter {
                $0.diagnostic.severity == .error
            }.count,
            warningCount: flat.filter {
                $0.diagnostic.severity == .warning
            }.count
        )
    }

    var diagnosticCount: Int { flatDiagnostics.count }

    var availableSources: [String] {
        Array(Set(flatDiagnostics.map(\.diagnostic.source))).sorted()
    }

    var presentationState: ProblemsPresentationState {
        if !flatDiagnostics.isEmpty { return .diagnostics }
        let states = normalizedDocumentStates()
        guard !states.isEmpty else { return .empty }
        let urls = states.compactMap { URL(string: $0.owner.uri) }
        let hasConfigSupport = urls.contains {
            ValidatorDetector.detect(for: $0) != nil
        }
        let lspLanguages = Set(urls.compactMap {
            LanguageServerRegistry.server(for: $0)?.language
        })
        guard hasConfigSupport || !lspLanguages.isEmpty else {
            return .unsupported
        }
        guard let lspManager else { return .empty }
        if !hasConfigSupport && !lspManager.enabled {
            return .disabled
        }
        if !hasConfigSupport
            && !lspLanguages.isDisjoint(
                with: lspManager.unavailableLanguages
            ) {
            return .unavailable
        }
        if lspLanguages.contains(where: {
            guard let state = lspManager.servers[$0]?.state else {
                return false
            }
            return state == .uninitialized || state == .initializing
        }) {
            return .loading
        }
        return .empty
    }

    var selectedDiagnostic: ProblemsFlatDiagnostic? {
        guard let selectedDiagnosticID else { return nil }
        return flatDiagnostics.first { $0.id == selectedDiagnosticID }
    }

    // MARK: - Panel visibility

    func togglePanel() {
        isPanelVisible.toggle()
    }

    func showPanel() {
        isPanelVisible = true
    }

    // MARK: - Navigation

    @discardableResult
    func nextDiagnostic() -> ProblemsFlatDiagnostic? {
        selectDiagnostic(offset: 1, initialIndex: 0)
    }

    @discardableResult
    func previousDiagnostic() -> ProblemsFlatDiagnostic? {
        let flat = flatDiagnostics
        return selectDiagnostic(
            offset: -1,
            initialIndex: max(0, flat.count - 1),
            diagnostics: flat
        )
    }

    func select(_ diagnostic: ProblemsFlatDiagnostic) {
        guard isCurrent(diagnostic) else {
            selectedDiagnosticID = nil
            return
        }
        selectedDiagnosticID = diagnostic.id
    }

    /// Revalidates the exact owner and producer revision immediately before
    /// navigation. A row captured before an edit, switch, close, pane move, or
    /// project change cannot redirect a different editor.
    func navigationTarget(
        for diagnostic: ProblemsFlatDiagnostic
    ) -> ProblemsNavigationTarget? {
        guard isCurrent(diagnostic) else { return nil }
        return ProblemsNavigationTarget(
            owner: diagnostic.owner,
            revision: diagnostic.revision,
            line: diagnostic.diagnostic.line,
            column: diagnostic.diagnostic.column
        )
    }

    // MARK: - Private aggregation helpers

    private var currentLSPDiagnostics: [LSPProblemsDiagnostics] {
        if let injectedLSPDiagnosticsProvider {
            return injectedLSPDiagnosticsProvider()
        }
        return lspManager?.allProblemsDiagnostics ?? []
    }

    private var filteredDiagnostics: [ProblemsFlatDiagnostic] {
        flatDiagnostics.filter { entry in
            let severityMatches = switch severityFilter {
            case .all: true
            case .error: entry.diagnostic.severity == .error
            case .warning: entry.diagnostic.severity == .warning
            case .info: entry.diagnostic.severity == .info
            }
            let sourceMatches = sourceFilter == nil
                || entry.diagnostic.source == sourceFilter
            return severityMatches && sourceMatches
        }
    }

    private func normalizedDocumentStates() -> [ProblemsDocumentState] {
        let supplied = documentStatesProvider?() ?? []
        let valid = supplied.filter { state in
            state.owner.projectID == projectID && !state.owner.uri.isEmpty
        }
        let ordered = valid.sorted(by: documentStatePrecedes)

        var seen: Set<ProblemsDocumentOwner> = []
        return ordered.filter { seen.insert($0.owner).inserted }
    }

    private func currentState(
        for owner: ProblemsDocumentOwner
    ) -> ProblemsDocumentState? {
        normalizedDocumentStates().first { $0.owner == owner }
    }

    private func pruneInvalidConfigRecords() {
        let states = normalizedDocumentStates()
        let validRevisions = Dictionary(
            uniqueKeysWithValues: states.map {
                ($0.owner, $0.contentRevision)
            }
        )
        configRecords = configRecords.filter { owner, record in
            validRevisions[owner] == record.revision
        }
    }

    private func makeEntry(
        owner: ProblemsDocumentOwner,
        revision: ProblemsDiagnosticRevision,
        origin: ProblemsDiagnosticOrigin,
        diagnostic: ValidationDiagnostic
    ) -> ProblemsFlatDiagnostic {
        ProblemsFlatDiagnostic(
            id: ProblemsDiagnosticID(
                uri: owner.uri,
                line: diagnostic.line,
                column: diagnostic.column,
                severityRank: severityRank(diagnostic.severity),
                source: diagnostic.source,
                message: diagnostic.message
            ),
            owner: owner,
            revision: revision,
            origin: origin,
            diagnostic: diagnostic
        )
    }

    private func isCurrent(_ entry: ProblemsFlatDiagnostic) -> Bool {
        guard entry.owner.projectID == projectID,
              let state = currentState(for: entry.owner) else {
            return false
        }

        switch entry.revision {
        case .editor(let revision):
            guard state.contentRevision == revision,
                  let record = configRecords[entry.owner],
                  record.revision == revision else {
                return false
            }
            return record.diagnostics.contains(entry.diagnostic)

        case .lsp(let documentVersion, let contentRevision):
            guard state.contentRevision == contentRevision else {
                return false
            }
            let matchingOwners = normalizedDocumentStates().filter {
                $0.owner.uri == entry.uri
            }
            guard matchingOwners.count == 1 else { return false }
            return currentLSPDiagnostics.contains { snapshot in
                snapshot.uri == entry.uri
                    && snapshot.documentVersion == documentVersion
                    && snapshot.contentRevision == contentRevision
                    && snapshot.diagnostics.contains(entry.diagnostic)
            }
        }
    }

    private func selectDiagnostic(
        offset: Int,
        initialIndex: Int,
        diagnostics suppliedDiagnostics: [ProblemsFlatDiagnostic]? = nil
    ) -> ProblemsFlatDiagnostic? {
        let flat = suppliedDiagnostics ?? filteredDiagnostics
        guard !flat.isEmpty else {
            selectedDiagnosticID = nil
            return nil
        }

        isPanelVisible = true
        let index: Int
        if let selectedDiagnosticID,
           let currentIndex = flat.firstIndex(where: {
               $0.id == selectedDiagnosticID
           }) {
            index = (currentIndex + offset + flat.count) % flat.count
        } else {
            index = initialIndex
        }
        selectedDiagnosticID = flat[index].id
        return flat[index]
    }

    private func clearSelectionIfInvalidated() {
        if let sourceFilter,
           !availableSources.contains(sourceFilter) {
            self.sourceFilter = nil
        }
        guard let selectedDiagnosticID,
              !flatDiagnostics.contains(where: {
                  $0.id == selectedDiagnosticID
              }) else {
            return
        }
        self.selectedDiagnosticID = nil
    }

    private func candidatePrecedes(_ lhs: Candidate, _ rhs: Candidate) -> Bool {
        let lhsEntry = lhs.entry
        let rhsEntry = rhs.entry
        if diagnosticPrecedes(lhsEntry, rhsEntry) { return true }
        if diagnosticPrecedes(rhsEntry, lhsEntry) { return false }
        if lhs.isFocusedOwner != rhs.isFocusedOwner {
            return lhs.isFocusedOwner
        }
        if lhsEntry.origin.rawValue != rhsEntry.origin.rawValue {
            return lhsEntry.origin.rawValue < rhsEntry.origin.rawValue
        }
        return ownerPrecedes(lhsEntry.owner, rhsEntry.owner)
    }

    private func diagnosticPrecedes(
        _ lhs: ProblemsFlatDiagnostic,
        _ rhs: ProblemsFlatDiagnostic
    ) -> Bool {
        if lhs.uri != rhs.uri { return lhs.uri < rhs.uri }
        if lhs.diagnostic.line != rhs.diagnostic.line {
            return lhs.diagnostic.line < rhs.diagnostic.line
        }
        let lhsColumn = lhs.diagnostic.column ?? 0
        let rhsColumn = rhs.diagnostic.column ?? 0
        if lhsColumn != rhsColumn { return lhsColumn < rhsColumn }
        let lhsSeverity = severityRank(lhs.diagnostic.severity)
        let rhsSeverity = severityRank(rhs.diagnostic.severity)
        if lhsSeverity != rhsSeverity { return lhsSeverity < rhsSeverity }
        if lhs.diagnostic.source != rhs.diagnostic.source {
            return lhs.diagnostic.source < rhs.diagnostic.source
        }
        return lhs.diagnostic.message < rhs.diagnostic.message
    }

    private func documentStatePrecedes(
        _ lhs: ProblemsDocumentState,
        _ rhs: ProblemsDocumentState
    ) -> Bool {
        if lhs.isFocusedPane != rhs.isFocusedPane {
            return lhs.isFocusedPane
        }
        return ownerPrecedes(lhs.owner, rhs.owner)
    }

    private func ownerPrecedes(
        _ lhs: ProblemsDocumentOwner,
        _ rhs: ProblemsDocumentOwner
    ) -> Bool {
        if lhs.uri != rhs.uri { return lhs.uri < rhs.uri }
        let lhsPane = lhs.paneID.id.uuidString
        let rhsPane = rhs.paneID.id.uuidString
        if lhsPane != rhsPane { return lhsPane < rhsPane }
        return lhs.tabID.uuidString < rhs.tabID.uuidString
    }

    private func severityRank(_ severity: ValidationSeverity) -> Int {
        switch severity {
        case .error: 0
        case .warning: 1
        case .info: 2
        }
    }
}
